//
// Generated by sedonac 0.1.0
// 12-May-2023 10:47
//

#ifndef SEDONAC_SEDONA_PLATFORM_H
#define SEDONAC_SEDONA_PLATFORM_H

#define PLATFORM_ID "tridium-generic-unix-0.1.0"
#define PLAT_BUILD_VERSION "0.1.0"

#endif
